# Generated by Django 3.2.8 on 2021-11-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='productID',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
