# Generated by Django 3.2.8 on 2021-12-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
